services:
  - type: web
    name: pinnacle-admin
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        scope: project
      - key: DATABASE_URL
        scope: project
      - key: PORT
        value: 5000

databases:
  - name: pinnacle-admin-db
    plan: free
    ipAllowList: []
